[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the dates in the migration files
# timezone = UTC

# max length of a revision id
# revision_id_length = 8

# sqlalchemy.url — сюда подставишь свою строку подключения
sqlalchemy.url = 
[post_write_hooks]
# Пример хука для форматирования файлов через black (если нужно)
# hook_name = python -m black %(filepath)s
